name: "Set up Poetry"
description: "Sets up Python and Poetry"

inputs:
  python-version:
    required: false
    description: "Version of Python to use"
    default: "3.13"
  poetry-version:
    required: false
    description: "Version of Poetry to use"
    default: "2.1.0"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: pipx install poetry==${{ inputs.poetry-version }}
      shell: bash
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"
